### ISSUE TITLE
The required JS dependency "scheduler" is not available

### ISSUE THREAD

**Issue by i-shm** [rome-user/tauri-clojurescript-template#2]
It seems the `scheduler` dependency is missing:

when I run `pnpm dev`:
```
...

[:app] Configuring build.
[:app] Compiling ...
[:app] Build failure:
The required JS dependency "scheduler" is not available, it was required by "node_modules/react-dom/cjs/react-dom.production.min.js".

Dependency Trace:
        app/core.cljs
        node_modules/react-dom/client.js
        node_modules/react-dom/index.js
        node_modules/react-dom/cjs/react-dom.production.min.js

Searched for npm packages in:
        /home/muqiu-han/Workspace/dashboard/node_modules

See: https://shadow-cljs.github.io/docs/UsersGuide.html#npm-install

...
```

**Comment by rome-user** [comment]
Hello, thanks for reporting. I do not use pnpm, but `scheduler` is a transitive dependency of `react-dom`. I am not sure why it is necessary to install it manually. I will have to investigate further

**Comment by rome-user** [comment]
OK, so I know that pnpm has issues with shadow-cljs. I decided to look at the Clojurians Slack and found this thread https://clojurians.slack.com/archives/C6N245JGG/p1681930425520199

From the thread,
> pnpm doesn't install peer-dependencies by default, the issue may not be clojure specify, but pnpm specific ...

There is also link to a discussion here https://github.com/orgs/pnpm/discussions/3995 . The important thing to note:

> Update pnpm to v7.1.3 or newer and set auto-install-peers to true.

Can you test this?

**Comment by i-shm** [comment]
tahks for reply!

I use pnpm 8.6.1, and set `auto-install-peers` to ture:

![image](https://github.com/rome-user/tauri-clojurescript-template/assets/66583620/117251f9-c4ba-4a5d-bcb9-d79eca91d75d)

But the issue still exists.

**Comment by rome-user** [comment]
I see. Does `pnpm dev` automatically install dependencies? 

I have only used `npm` and `yarn`, and no missing dependencies are reported with these tools.

**Comment by rome-user** [comment]
Okay, I have taken a closer look at pnpm compatibility with shadow-cljs. It looks like the way pnpm structures node_modules folder is not compatible with shadow-cljs.

I recommend using `npm` or `yarn` instead. If you want to use `pnpm` anyway, I recommend the following command as a workaround.

```
pnpm install --force --shamefully-flatten
```

Then run `pnpm dev`.

**Comment by i-shm** [comment]
Thank you very much for your answer!
